version: "3"

services:
  app:
    ports:
      - 8080
    environment:
      MYSQL_DATABASE: app_dev
      MYSQL_USER: app_dev

  mailhog:
    image: mailhog/mailhog
    hostname: mailhog
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - internal
      - external